query GetSubject($subjectId: ID!) {
	getSubject(id: $subjectId) {
		name
		currentLevel
		id
		lessons {
			id
			title
			shortDescription
			content
			showSideFirst
			reviewDate
			cards {
				id
				side1
				side2
				interval
				status
				nextRepetition
				numRepetitions
			}
			subject {
				id
				name
				currentLevel
			}
		}
	}
}
