query GetLesson($lessonId: ID!) {
	getLesson(id: $lessonId) {
		id
		title
		shortDescription
		content
		showSideFirst
		reviewDate
		reviewDeck {
			nextRepetition
			side1
			side2
			interval
			numRepetitions
			status
			id
		}
		cards {
			nextRepetition
			side1
			side2
			interval
			status
			numRepetitions
			id
		}
		subject {
			id
			name
			currentLevel
		}
	}
}
